[refactor] City, Map 검증 리팩토링
UMC-TripPiece/TripPiece-backend pull request #82
Opened 2024-11-24 14:38 UTC by StoneCAU

## 개요

City, Map 검증 과정 및 기타 코드 리팩토링

<br/>

## ✅ 작업 내용

- [x] City: RequestDto에서 NotBlank를 통해 검증
- [x] Map: lombok 사용, 커스텀 어노테이션을 통한 검증
- [x] 기타: RequiredArgsConstructor를 통한 생성자 주입으로 통일

- Map 삭제 API에서의 커스텀 어노테이션 작동
<img width="754" alt="image" src="https://github.com/user-attachments/assets/ccc4f042-a793-4513-9452-793cc4dd2158">

<br/>

### 📝 논의사항

추 후 개발사항
- ApiResponse를 통한 응답으로 통일
- 모든 input 값을 requestDto에서 검증하도록 변경
- 커스텀 어노테이션 추가 예정

2024-11-26 18:04 UTC, yyypearl requested changes

2024-11-26 18:09 UTC, yyypearl approved these changes

2024-11-26 18:09 UTC, yyypearl commented on src/main/java/umc/TripPiece/validation/annotation/ExistCity.java
annotation을 엔티티별로 구분한 이유가 있을까요? 현재는 코드도 로직도 동일해보여서 공통 어노테이션으로 바꿀 수도 있지 않을까 싶은데 확장성을 고려한 것인지 궁금해요!

2024-11-26 18:09 UTC, yyypearl approved these changes

2024-11-26 18:10 UTC, yyypearl approved these changes

2024-11-26 18:10 UTC, yyypearl commented on src/main/java/umc/TripPiece/apiPayload/code/status/ErrorStatus.java
ErrorStatus랑 SuccessStatus 너무 좋습니다!!👍🏻😀

2024-11-26 18:12 UTC, yyypearl commented
세팅부터 리팩토링까지 고생 많으셨습니다~!! 코드도 많네요. 머지하겠습니다🤟🏻

2024-11-26 18:12 UTC, merged

2024-11-27 14:05 UTC, StoneCAU commented on src/main/java/umc/TripPiece/validation/annotation/ExistCity.java
공동 어노테이션으로 묶으면 더 좋을 것 같긴해요. 
근데 저는 어떻게 구현할 지 감이 안잡히네요 ㅠㅠ
단순히 Long 값(id)만을 전달받는데 검증 클래스에서 그 값이 어떤 엔티티의 id인지 알 수 있을까요? 좋은 방법이 있으시면 공유부탁드립니다!!!